Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20190826041533_devise_create_users.rb
db/schema.rb
test/models/user_test.rb

- added gem 'device'
- set up User model
- generated device views
- added login logic

first codebase setup

---

app/models/animal.rb
db/migrate/20190826050002_create_animals.rb
db/schema.rb
test/models/animal_test.rb

- generated model without photo variable

created animal model

---

.gitignore
Gemfile
Gemfile.lock
app/models/animal.rb
app/uploaders/photo_uploader.rb
db/migrate/20190826054834_add_photo_to_animals.rb
db/schema.rb

added photo migration
added gems
created env file
added cloudinary key

Photo migration

---

db/migrate/20190826055520_add_user_to_animals.rb
db/schema.rb

- forgot to add references to animal model before
- created new migration to add user references to animal table

generated migration to add user reference in animals table

---

README.md
db/seeds.rb

user added to seed

---

app/controllers/animals_controller.rb
app/views/animals/index.html.erb
config/routes.rb
test/controllers/animals_controller_test.rb

Animal routes

---

app/controllers/animals_controller.rb
app/views/animals/index.html.erb
test/controllers/animals_controller_test.rb

add index in the controller and index.html.erb

animal controller with index action

---

app/controllers/animals_controller.rb
app/views/animals/show.html.erb

added animal show in controller and added show.html.erb

added animal_show

---

app/controllers/animals_controller.rb
app/views/animals/new.html.erb

added new&create in controller.
added new.html.erb

added animal_create

---

app/controllers/animals_controller.rb

destroy in controller added.
Couldn't get the view working.

destroy added

---

app/views/animals/show.html.erb

- added very basic container to center the content
- added buttons for delete and edit actions

added very basic bootstrap to animal show view

---

app/models/review.rb
db/migrate/20190827050628_create_reviews.rb
db/schema.rb
test/models/review_test.rb

- started to work on the review feature
- created review model and associated migration
- added validations

created review model and added validations

---

db/seeds.rb

- added these three characteristics, so Robin can work with something on the front-end for the show page

added species, price, and description for animal to seeds file

---

app/controllers/therapies_controller.rb
app/models/animal.rb
app/models/therapy.rb
app/models/user.rb
app/views/therapies/_form.html.erb
app/views/therapies/index.html.erb
app/views/therapies/new.html.erb
config/routes.rb
db/migrate/20190827012509_create_therapies.rb
db/schema.rb
test/controllers/therapies_controller_test.rb
test/models/therapy_test.rb

fixed the routes for therapy: animal->id->therapies->new
checked animal->id>therapies------->>>>> worked
Let's check why it cannot automatically merge.

Fix animal therapy routes

---

Gemfile
Gemfile.lock
app/controllers/therapies_controller.rb
app/models/animal.rb
app/models/therapy.rb
app/models/user.rb
app/views/therapies/_form.html.erb
app/views/therapies/index.html.erb
app/views/therapies/new.html.erb
config/routes.rb
db/migrate/20190827012509_create_therapies.rb
db/schema.rb
test/controllers/therapies_controller_test.rb
test/models/therapy_test.rb

!!!!!!
gem installed : gem 'validates_overlap'
!!!!!!
do a bundle install
fixed overlap of the therapy: cannot set the same day booking.

Fix overlap therapy

---

app/controllers/reviews_controller.rb
db/schema.rb
test/controllers/reviews_controller_test.rb

- only created reviews controller

Create review controller

---

app/controllers/therapies_controller.rb
app/views/therapies/index.html.erb
db/schema.rb

fixed price calculation for multiply nights

price fixed

---

app/controllers/therapies_controller.rb
app/views/dashboard/show.html.erb
app/views/therapies/edit.html.erb
app/views/therapies/show.html.erb
config/routes.rb

can check --> edit and delete therapy

Tidy dash board

---

app/views/animals/_edit.html.erb
app/views/animals/show.html.erb

create modal for edit

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_map.scss
app/controllers/animals_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_mapbox.js
app/models/animal.rb
app/views/animals/index.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

- map display on animals' index page

Implement map
